services:
  db:
    image: postgres:15.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    container_name: ${DOCKER_CONTAINER_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data